version: "3.9"

services:
  steamidp:
    image: ghcr.io/byo-software/steam-openid-connect-provider:latest
    container_name: steamidp
    ports:
      - "8080:80"
    environment:
      Steam__ApplicationKey: your_steam_api_key
      OpenId__ClientId: steam-client
      OpenId__ClientName: Steam
      OpenId__ClientSecret: steam-secret
      OpenId__RedirectUri: http://localhost:3000/api/auth/callback
